services:
  doom-ai-app:
    build:
      context: .
      dockerfile: docker_files/agent_backend.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - EPOCHS=10